Zadanie/16.3
Geometric7/shirt_personalizer_react pull request #1
Opened 2022-01-09 15:51 UTC by Geometric7

2022-01-10 08:35 UTC, lduraj90 commented
1. Po zagnieżdżaj w sobie poszczególne katalogi. Wewnątrz katalogu Products daj katalog Product, a w nim ProductImage i ProductForm. Komponenty ze sobą wzajemnie powiązane powinny dzielić wspólną przestrzeń. 
2. We wszystkich stworzonych podkomponentach brakuje PropTypesów

2022-01-10 08:37 UTC, lduraj90 requested changes

2022-01-10 08:37 UTC, lduraj90 commented on src/components/OptionColor/OptionColor.js
> +        {colors.map(color => <li key={shortid()}><button type="button" onClick={() => setCurrentColor(color)} className={clsx(prepareColorClassName(color), currentColor === color && styles.active)} /
Z formatuj ten kod, aby był bardziej czytelny. kolejne atrybuty umieść pod sobą, np,
```
<li
   key=...
   className=...
   onClick=...
></li>```

2022-01-10 23:23 UTC, Geometric7 commented on src/components/OptionColor/OptionColor.js
> +        {colors.map(color => <li key={shortid()}><button type="button" onClick={() => setCurrentColor(color)} className={clsx(prepareColorClassName(color), currentColor === color && styles.active)} /
Teraz powinno być ok

2022-01-11 10:27 UTC, lduraj90 approved these changes

2022-01-13 21:02 UTC, merged